### ISSUE TITLE
zsh: command not found: nchat

### ISSUE THREAD

**Issue by shinokada** [irrationalistic/nchat#1]
Hi, I just install nchat. I run `nchat -s -u shin` on a terminal, but it gives command not found: nchat.

What am I doing wrong here? Thank you for your help.

**Comment by irrationalistic** [comment]
Just to confirm, you installed it using NPM? `npm install -g nchat`? If that errors out, try `sudo npm install -g nchat`?

**Comment by irrationalistic** [comment]
Have you had any luck with this?

**Comment by irrationalistic** [comment]
I'm going to close this since it's been nearly a month!
